name: nft_marketplace
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexagon: ^0.2.0-nullsafety.1
  font_awesome_flutter: ^9.0.0
  page_transition: ^2.0.5
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.4
  #web3dart: ^2.7.1
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  dio: ^5.3.2
  get_it: ^7.6.0
  go_router: ^10.1.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.1
  #google_fonts: any
  shared_preferences: ^2.2.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: gothic
      fonts:
        - asset: assets/font_styles/century_gothic.ttf
    - family: montserrat_regular
      fonts:
        - asset: assets/font_styles/montserrat_regular.ttf
          #weight: 600
    - family: montserrat_bold
      fonts:
        - asset: assets/font_styles/montserrat_bold.ttf
          #weight: 600

  assets:
    - assets/images/
    - assets/images/sb19/
    - assets/images/my_hub/
    - assets/images/meet_your_community/
    - assets/images/event_ticket/
    - assets/images/favorite_collection/
    - assets/images/shout_out/
    - assets/images/carousel_images/
    - assets/images/ranking_community/
    - assets/images/ranking_entertainer/
    - assets/images/ranking_fan/
    - assets/images/others/
    - assets/images/market_place/
    - assets/images/profile/
    - assets/images/community/
    - assets/images/app_logo/
 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo/fanhub_logo2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo/fanhub_logo2.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logo/fanhub_logo2.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo/fanhub_logo2.png"